# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 672c8c1b48988a8e9434e0caa062dc4477d493e9c3ef70505286d705b6eb95dbb7a72c4a1a366cada1e7fb1af146a62bbb1b0dad2ee3fe565711758fc2a18c8b

test:
  secret_key_base: 11919dddb91fcfd237648f898cb5e87aac03c2f61229ab2b22629f436cb9760fa72315633c813cead3c4ffcd61d4ecd00e5bdf1523942fc78f254f09968034fd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
